version: "3"

services:
  paymob-accept-backend:
    # command: gunicorn --workers=4 --threads=4 --timeout 600 --bind 0.0.0.0:8000 paymob_accept.wsgi:application
    command: python manage.py runserver 0.0.0.0:8000
    image: paymob-accept-backend
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    networks:
      - nginx_network
      - database_network
      - redis_network
    depends_on:
      - db
  db:
    image: postgres:12.3
    env_file:
      - ./.env.db
    networks:
      - database_network
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis_network


  nginx:
    build: ./nginx
    environment:
      - DJANGOAPP=http://paymob-accept-backend:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8089:80
    depends_on:
      - paymob-accept-backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
  media_volume:
