version: "3.4"

services:
  nginx:
    image: clientip/nginx:local
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    ports:
      - 801:80
    depends_on:
      - nodejs-app

  nodejs-app:
    image: clientip/nodejsapp:local
    build:
      context: "./app/"
      dockerfile: Dockerfile
    environment:
      - "PORT=80"

networks:
  default:
    external:
      name: clientip-troublshooting